/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_790620_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_790620_2[] = { " pure camomile", " thoroughly minted infusion", "Berry Burst", "darjeeling blend", "decaf nutmeg and vanilla", "earl grey", "english breakfast tea", "fresh orange", "garden slection (lemon)", "green tea", "raspberry", "sweet cherry" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_790620_2_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };
const uint32_t ei_dsp_config_790620_2_axes_size = 12;
ei_dsp_config_raw_t ei_dsp_config_790620_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    12, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_790620_2[12] = { 29.261136781682342, 56.896767211426216, 976.4258971409095, 798047.6518650089, 28.534298386921044, 50.944369375388106, 975.270567871961, 1691329.3960923622, 0.7268206018484719, 5.952078155736516, 1.1554174083376016, -496395.7175843695 };
const float ei_dn_standard_scaler_scale_790620_2[12] = { 0.320960497188698, 0.0836209953451369, 3.318369481953736, 0.00000781842235081887, 0.3569139881802536, 0.09389976390326722, 2.882329720788828, 0.000006091922126987532, 1.9644776006994458, 0.26030133305780595, 4.506251880888278, 0.000006407279226225772 };
const float ei_dn_standard_scaler_var_790620_2[12] = { 9.707263796691784, 143.01096417309083, 0.09081352190605281, 16359188077.25715, 7.8500579300829, 113.41513116999253, 0.1203684533339523, 26945814380.693924, 0.2591229250379972, 14.75866977575157, 0.049245785979493716, 24358621016.13872 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_790620_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_790620_2,
    .mean_data_len = 12,
    .scale_data = (float *)ei_dn_standard_scaler_scale_790620_2,
    .scale_data_len = 12,
    .var_data = (float *)ei_dn_standard_scaler_var_790620_2,
    .var_data_len = 12
};
ei_data_normalization_t ei_data_normalization_config_790620_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_790620_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_790620_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_790620_2[ei_dsp_blocks_790620_2_size] = {
    { // DSP block 2
        2,
        12, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_790620_2, // pointer to config struct
        ei_dsp_config_790620_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_790620_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_790620_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_790620_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_790620_3_init,
    .model_invoke = &tflite_learn_790620_3_invoke,
    .model_reset = &tflite_learn_790620_3_reset,
    .model_input = &tflite_learn_790620_3_input,
    .model_output = &tflite_learn_790620_3_output,
};

const uint8_t ei_output_tensors_indices_790620_3[1] = { 0 };
const uint8_t ei_output_tensors_size_790620_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_790620_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_790620_3,
    .output_tensors_size = ei_output_tensors_size_790620_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_790620_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_790620_2_size = 1;
const uint32_t ei_learning_block_790620_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_790620_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_790620_2[ei_learning_blocks_790620_2_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_790620_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_790620_3_inputs,
        ei_learning_block_790620_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_790620_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_790620_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_790620_2[ei_postprocessing_blocks_790620_2_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_790620_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_790620_2_size = 0;

uint32_t *freeform_outputs_790620_2 = nullptr;

const ei_impulse_t impulse_790620_2 = {
    .project_id = 790620,
    .project_owner = "jmr00004",
    .project_name = "iScent",
    .impulse_id = 2,
    .impulse_name = "iScent Impulse",
    .deploy_version = 1,

    .nn_input_frame_size = 12,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 12,
    .dsp_input_frame_size = 1 * 12,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_790620_2_size,
    .dsp_blocks = ei_dsp_blocks_790620_2,

    .learning_blocks_size = ei_learning_blocks_790620_2_size,
    .learning_blocks = ei_learning_blocks_790620_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_790620_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_790620_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temp1 + hum1 + pres1 + gas1_0 + temp2 + hum2 + pres2 + gas2_0 + delta_temp + delta_hum + delta_pres + delta_gas",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 12,
    .categories = ei_classifier_inferencing_categories_790620_2,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_790620_2_size,
    .freeform_outputs = freeform_outputs_790620_2
};

ei_impulse_handle_t impulse_handle_790620_2 = ei_impulse_handle_t( &impulse_790620_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_790620_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_790620_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_790620_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_790620_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
