/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_790620_25_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_790620_6[] = { "Coffee", "Decaf Coffee", "Decaf Tea", "Tea", "ambient" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_790620_23_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 };
const uint32_t ei_dsp_config_790620_23_axes_size = 24;
ei_dsp_config_raw_t ei_dsp_config_790620_23 = {
    23, // uint32_t blockId
    1, // int implementationVersion
    24, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_790620_23[24] = { 12358782.34856176, 4001075.2131979694, 1937581.834179357, 1024208.5583756345, 685741.820642978, 499548.7461928934, 359213.81556683587, 306906.3637901861, 328117.27072758036, 341743.69204737735, 10474994.509306261, 3778256.1049069376, 1393060.780033841, 736580.9661590524, 424450.93062605755, 348991.1116751269, 272525.35532994923, 215206.5228426396, 244951.48223350252, 259347.42978003385, 0.46241962646217716, -0.04741116683117024, 1.096395941958613, 369455.4568527919 };
const float ei_dn_standard_scaler_scale_790620_23[24] = { 1.8804483941561634e-7, 6.611257771317289e-7, 0.0000012783204571698882, 0.000002705192531327572, 0.000004700412887968377, 0.000006969460196454697, 0.000009656343960849368, 0.00001284815523181785, 0.000012757139234748024, 0.00001255282168552789, 2.6010202392372547e-7, 8.5833723420582e-7, 0.000002129961028151577, 0.000004244910672474491, 0.000007830004389902758, 0.000010991368906159139, 0.000015538596373236184, 0.000020850517373117525, 0.00001919464809338501, 0.000019074164514372354, 4.287395283904938, 0.3518142451949562, 20.94313344371962, 0.0000031188204305018195 };
const float ei_dn_standard_scaler_var_790620_23[24] = { 28279853880249.05, 2287872504154.0063, 611956457446.2433, 136648113545.27536, 45261400006.40775, 20587410101.688553, 10724438077.487123, 6057849083.52417, 6144597062.275267, 6346251523.671661, 14781296779256.688, 1357325771831.9297, 220422886616.24237, 55496154268.59778, 16310827281.154234, 8277447427.4900675, 4141678929.714686, 2300203862.7638607, 2714186532.8114433, 2748583605.9878774, 0.054401759753715584, 8.079289297023259, 0.002279904627835555, 102806188703.38861 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_790620_23 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_790620_23,
    .mean_data_len = 24,
    .scale_data = (float *)ei_dn_standard_scaler_scale_790620_23,
    .scale_data_len = 24,
    .var_data = (float *)ei_dn_standard_scaler_var_790620_23,
    .var_data_len = 24
};
ei_data_normalization_t ei_data_normalization_config_790620_23 = {
    (void *) &ei_data_normalization_standard_scaler_config_790620_23, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_790620_6_size = 1;
ei_model_dsp_t ei_dsp_blocks_790620_6[ei_dsp_blocks_790620_6_size] = {
    { // DSP block 23
        23,
        24, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_790620_23, // pointer to config struct
        ei_dsp_config_790620_23_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_790620_23_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_790620_23, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_790620_25 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_790620_25_init,
    .model_invoke = &tflite_learn_790620_25_invoke,
    .model_reset = &tflite_learn_790620_25_reset,
    .model_input = &tflite_learn_790620_25_input,
    .model_output = &tflite_learn_790620_25_output,
};

const uint8_t ei_output_tensors_indices_790620_25[1] = { 0 };
const uint8_t ei_output_tensors_size_790620_25 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_790620_25 = {
    .implementation_version = 1,
    .block_id = 25,
    .output_tensors_indices = ei_output_tensors_indices_790620_25,
    .output_tensors_size = ei_output_tensors_size_790620_25,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_790620_25,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_790620_6_size = 1;
const uint32_t ei_learning_block_790620_25_inputs[1] = { 23 };
const uint8_t ei_learning_block_790620_25_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_790620_6[ei_learning_blocks_790620_6_size] = {
    {
        25,
        &run_nn_inference,
        (void*)&ei_learning_block_config_790620_25,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_790620_25_inputs,
        ei_learning_block_790620_25_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_790620_25 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_790620_6_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_790620_6[ei_postprocessing_blocks_790620_6_size] = {
    {
        .block_id = 25,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_790620_25,
        .input_block_id = 25
    },
};

const uint8_t freeform_outputs_790620_6_size = 0;

uint32_t *freeform_outputs_790620_6 = nullptr;

const ei_impulse_t impulse_790620_6 = {
    .project_id = 790620,
    .project_owner = "jmr00004",
    .project_name = "iScent",
    .impulse_id = 6,
    .impulse_name = "Impulse #6",
    .deploy_version = 3,

    .nn_input_frame_size = 24,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 24,
    .dsp_input_frame_size = 1 * 24,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_790620_6_size,
    .dsp_blocks = ei_dsp_blocks_790620_6,

    .learning_blocks_size = ei_learning_blocks_790620_6_size,
    .learning_blocks = ei_learning_blocks_790620_6,

    .postprocessing_blocks_size = ei_postprocessing_blocks_790620_6_size,
    .postprocessing_blocks = ei_postprocessing_blocks_790620_6,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "gas1_0 + gas1_1 + gas1_2 + gas1_3 + gas1_4 + gas1_5 + gas1_6 + gas1_7 + gas1_8 + gas1_9 + gas2_0 + gas2_1 + gas2_2 + gas2_3 + gas2_4 + gas2_5 + gas2_6 + gas2_7 + gas2_8 + gas2_9 + delta_temp + delta_hum + delta_pres + delta_gas",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 5,
    .categories = ei_classifier_inferencing_categories_790620_6,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_790620_6_size,
    .freeform_outputs = freeform_outputs_790620_6
};

ei_impulse_handle_t impulse_handle_790620_6 = ei_impulse_handle_t( &impulse_790620_6 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_790620_6;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_790620_6;
const auto ei_dsp_blocks_size = ei_dsp_blocks_790620_6_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_790620_6;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
